# generate a github action to build debian docker image
# and push to etma/devcontainer
name: Debian-python-kube-base
on:
  schedule:
    - cron: '1 0 * * *'
  push:
    paths:
      - .github/workflows/debian-python-kube-base.yaml
      - containers/debian-kube-base.Dockerfile
      - .dockerignore
      - containers/shell/**
  pull_request:
    paths:
      - .github/workflows/debian-python-kube-base.yaml
      - containers/debian-kube-base.Dockerfile
      - .dockerignore
      - containers/shell/**

jobs:
  base:
    runs-on: devcontainer-python-arc-set
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to dockerhub to avoid rate limits
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v2

      - run: docker context create builders

      - uses: docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: builders

      - name: Build and push base image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./containers/debian-kube-base.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            CREATED=$(date -u +%Y-%m-%dT%H:%M:%SZ)
            REVISION=$(git rev-parse --short HEAD)
            VERSION=ubuntu-latest
          tags: |
            etma/devcontainer-python:debian-kube-base
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
