# generate a github action to build ubuntu docker image
# and push to etma/devcontainer
name: Ubuntu-python
on:
  schedule:
    - cron: '1 0 * * *'
  push:
    paths:
      - .github/workflows/ubuntu-python.yaml
      - containers/ubuntu.Dockerfile
      - containers/ubuntu-base.Dockerfile
      - .dockerignore
      - containers/shell/**
  pull_request:
    paths:
      - .github/workflows/ubuntu-python.yaml
      - containers/ubuntu.Dockerfile
      - containers/ubuntu-base.Dockerfile
      - .dockerignore
      - containers/shell/**

jobs:
  verify:
    runs-on: ubuntu-latest
    needs: ['base']
    steps:
      - uses: actions/checkout@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to dockerhub to avoid rate limits
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Ubuntu
        run: docker build --build-arg PYTHON_VERSION=3.12 -t etma/devcontainer-python:ubuntu -f ./containers/ubuntu.Dockerfile .
  base:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to dockerhub to avoid rate limits
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v2

      - run: docker context create builders

      - uses: docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: builders

      - name: Build and push base image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./containers/ubuntu-base.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            CREATED=$(date -u +%Y-%m-%dT%H:%M:%SZ)
            REVISION=$(git rev-parse --short HEAD)
            VERSION=ubuntu-latest
          tags: |
            etma/devcontainer-python:ubuntu-base
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
  gather:
    runs-on: ubuntu-latest
    needs: ['base', 'verify']
    outputs:
      python-versions: ${{ steps.get-python-versions.outputs.python-versions }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: asdf-vm/asdf.git
          path: ./.asdf
          ref: v0.11.0

      - name: Install zsh
        run: sudo apt-get update && sudo apt-get install -y zsh

      - name: Get python versions
        id: get-python-versions
        run: docker run continuumio/anaconda3 conda search python | grep -v Name | grep -v '^$' | grep -v 'channels:' | awk '{print $2}' | sort -V | uniq > $GITHUB_OUTPUT
        shell: zsh {0}

  latest:
    runs-on: ubuntu-latest
    needs: ['base', 'verify']
    if: github.event_name == 'push'
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to dockerhub to avoid rate limits
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v2

      - run: docker context create builders

      - uses: docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: builders

      - name: set variables
        id: vars
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          TAG=${GITHUB_REF#refs/tags/}
          echo commit=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT
          echo created=$(date -u +%Y-%m-%dT%H:%M:%SZ) >> $GITHUB_OUTPUT
          if [ "$TAG" != "$GITHUB_REF" ]; then
            echo version=ubuntu-latest-$TAG >> $GITHUB_OUTPUT
            echo ubuntu_version=ubuntu-$TAG >> $GITHUB_OUTPUT
            echo platforms=linux/amd64,linux/arm64 >> $GITHUB_OUTPUT
            echo main=true >> $GITHUB_OUTPUT
          elif [ "$BRANCH" = "main" ]; then
            echo version=ubuntu-latest >> $GITHUB_OUTPUT
            echo ubuntu_version=ubuntu >> $GITHUB_OUTPUT
            echo platforms=linux/amd64,linux/arm64 >> $GITHUB_OUTPUT
            echo main=true >> $GITHUB_OUTPUT
          else
            echo version=ubuntu-latest-$BRANCH >> $GITHUB_OUTPUT
            echo ubuntu_version=ubuntu-$BRANCH >> $GITHUB_OUTPUT
            echo platforms=linux/amd64,linux/arm64 >> $GITHUB_OUTPUT
            echo main=false >> $GITHUB_OUTPUT
          fi

      - name: Build and push final image
        uses: docker/build-push-action@v3
        if: ${{ steps.vars.outputs.main }}
        with:
          context: .
          file: ./containers/ubuntu.Dockerfile
          platforms: ${{ steps.vars.outputs.platforms }}
          push: true
          build-args: |
            CREATED=${{ steps.vars.outputs.created }}
            REVISION=${{ steps.vars.outputs.commit }}
            VERSION=${{ steps.vars.outputs.version }}
            PYTHON_VERSION=3.12
          tags: |
            etma/devcontainer-python:${{ steps.vars.outputs.version }}
            etma/devcontainer-python:${{ steps.vars.outputs.ubuntu_version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

  publish:
    runs-on: ubuntu-latest
    needs: ['verify', 'gather','base']
    if: github.event_name == 'push'
    permissions:
      packages: write
    strategy:
      max-parallel: 10
      matrix:
        python-version: ${{ fromJson(needs.gather.outputs.python-versions) }}
    steps:
      - uses: actions/checkout@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to dockerhub to avoid rate limits
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v2

      - run: docker context create builders

      - uses: docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: builders

      - name: set variables
        id: vars
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          TAG=${GITHUB_REF#refs/tags/}
          echo commit=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT
          echo created=$(date -u +%Y-%m-%dT%H:%M:%SZ) >> $GITHUB_OUTPUT
          if [ "$TAG" != "$GITHUB_REF" ]; then
            echo version=${{ matrix.python-version }}-$TAG >> $GITHUB_OUTPUT
            echo ubuntu_version=${{ matrix.python-version }}-ubuntu-$TAG >> $GITHUB_OUTPUT
            echo platforms=linux/amd64,linux/arm64 >> $GITHUB_OUTPUT
            echo main=true >> $GITHUB_OUTPUT
          elif [ "$BRANCH" = "main" ]; then
            echo version=${{ matrix.python-version }}-ubuntu-latest >> $GITHUB_OUTPUT
            echo ubuntu_version=${{ matrix.python-version }}-ubuntu >> $GITHUB_OUTPUT
            echo platforms=linux/amd64,linux/arm64 >> $GITHUB_OUTPUT
            echo main=true >> $GITHUB_OUTPUT
          else
            echo version=${{ matrix.python-version }}-$BRANCH >> $GITHUB_OUTPUT
            echo ubuntu_version=${{ matrix.python-version }}-ubuntu-$BRANCH >> $GITHUB_OUTPUT
            echo platforms=linux/amd64,linux/arm64 >> $GITHUB_OUTPUT
            echo main=false >> $GITHUB_OUTPUT
          fi

      - name: Build and push final image
        uses: docker/build-push-action@v3
        if: ${{ steps.vars.outputs.main }}
        with:
          context: .
          file: ./containers/ubuntu.Dockerfile
          platforms: ${{ steps.vars.outputs.platforms }}
          push: true
          build-args: |
            CREATED=${{ steps.vars.outputs.created }}
            REVISION=${{ steps.vars.outputs.commit }}
            VERSION=${{ steps.vars.outputs.version }}
            PYTHON_VERSION=${{ matrix.python-version }}
          tags: |
            etma/devcontainer-python:${{ steps.vars.outputs.version }}
            etma/devcontainer-python:${{ steps.vars.outputs.ubuntu_version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
